version: '3.7'
services:
  postgres:
    image: postgres:14-alpine3.15
    environment:
      POSTGRES_DB: ikea-inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
